# serverless.yml

component: "website"
name: uct-h5
app: uct-components # (可选) 该 nuxt.js 项目名称
stage: test # (可选) 用于区分环境信息，默认值是 dev
inputs:
  src:
    src: ./unpackage/dist/build/h5 # Upload static files
    index: index.html
  region: ap-guangzhou
  bucketName: uct-h5
  cors:
    - allowedOrigins:
        - "*"
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - HEAD
      allowedHeaders: "*"
      maxAgeSeconds: 10
